name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'oracle'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Runnable Jar
          path: staging

      # Step to create a tag
      - name: Create Git Tag
        run: |
          TAG_NAME="v1.0.0" # Update this version as needed
          git tag $TAG_NAME
          git push origin $TAG_NAME

      # Create the release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/master') }}
        with:
          body: This is your body here
          files: staging/*.jar
