name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'oracle'
      - run: mvn --batch-mode --update-snapshots verify

      # Debugging step: Check if the artifact is created
      - run: mkdir staging && cp target/*.jar staging
      - run: ls -al staging

      # Create a release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v1.0.0"  # Change the tag as appropriate
          release_name: "Release v1.0.0"  # Customize the release name
          draft: false
          prerelease: false
